openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that allows a user to ask questions of and interact with the news.
  version: 'v1'
servers:
  - url: http://localhost:8080
paths:
  /query:
    get:
      operationId: query
      summary: Retrieves a list of URL links to the news articles that are most relevant to the user's query, and a summarized answer to the user's query based on the sources. Display results as a list of link previews with images and the text answer below.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: The query to be answered
        - in: query
          name: topic
          required: true
          schema:
            $ref: '#/components/schemas/Topic'
      description: >
        This endpoint takes in a query from the user about a question about the news to be answered and the topic, and responds with a JSON object containing an answer to the user's query, a list of source URLs that the answer is based on, and optionally a list of follow up queries.
      responses:
         '200':
          description: A successful response with an answer to the user's query and a list of source URLs used to answer the query, and optionally a list of follow up queries the user can ask.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: This is the answer to the user's query.
                  sources:
                    type: array
                    items: 
                      type: object
                      properties:
                        url:
                          type: string
                          description: The URL of the source.
                        title:
                          type: string
                          description: The title of the source.
                        top_image_url:
                          type: string
                          description: The URL of the image to display for the link.
                    description: This is a list of sources used to answer the user's query, with the title, url and image url for the query.
                  followup_queries:
                    type: array
                    items: 
                      type: string
                    description: This is a list of followup queries that the user can ask to get more information about the answer.
                required:
                  - answer
                  - sources
              example:
                message: "Biden is the current president of the United States"
                sources:
                  - url: "https://www.nytimes.com/spotlight/joe-biden"
                  - title: "Joe Biden - The New York Times"
                  - top_image_url: "https://static01.nyt.com/images/2021/01/20/us/politics/20dc-biden-inauguration-01/20dc-biden-inauguration-01-facebookJumbo.jpg"
          '400':
            description: Bad request (e.g., missing or invalid query parameter)
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      description: The status of the response
                    message:
                      type: string
                      description: A message describing the error
components:
  schemas:
    Topic:
      type: string
      enum:
        - nba
        - tech
        - general
        - unknown